### ISSUE TITLE
SSL Encryption Issue

### ISSUE THREAD

**Issue by Sydnee510** [Sydnee510/facts_app#5]
When the SSL encryption is set to Flexible, user authentication does not work on the site. We get an error that says "the change you wanted was rejected" *photo attached below
![Screen Shot 2020-12-24 at 10 23 30 AM](https://user-images.githubusercontent.com/30539832/113400300-6cfe2e80-9356-11eb-9b3e-d1026c9c6129.png)

When SSL mode is set to OFF or not secure, user authentication works but the site shows that it is not secure.

**Comment by chayadeaver** [comment]
I found this article that may help. It looks like SSL isn't enabled in this app yet. https://stackify.com/how-to-configure-https-for-ruby-on-rails-ror/

**Comment by Sydnee510** [comment]
https://devcenter.heroku.com/articles/automated-certificate-management used this doc and was able to get it set up. This issue will be closed now.
